from __future__ import annotations


TRANSLATIONS: dict[str, dict[str, str]] = {
    "zh": {
        "app_title": "5AxisSclicer V2.0 五轴切片工作台",
        "workbench_home": "工作台",
        "manufacturing_setup_entry": "公共制造设置",
        "home_title": "五轴塑料/树脂增材工作台",
        "home_subtitle": "首次使用：打开 STEP → 公共制造设置（Part、喷嘴、材料、坐标）→ 选择工作台 → 生成、检查并导出 NC。",
        "load_demo": "打开叶轮项目",
        "gcode_viewer_entry": "切片成果预览",
        "open_step": "打开 STEP",
        "open_project": "打开项目",
        "open_gcode": "打开 NC/G-code",
        "save": "保存项目",
        "clear": "清空选择",
        "fit": "适配视图",
        "home_view": "初始视角",
        "language": "English",
        "operation": "操作类型",
        "tube_coordinate_entry": "进入管状设置（定义坐标）",
        "operation_imported_nc": "Imported NC Review（导入路径检查）",
        "operation_curve": "Curve Buildup",
        "operation_freeform": "Freeform Coating",
        "model_file": "STEP 模型",
        "gcode_file": "NC/G-code",
        "file_none": "未载入",
        "tab_objects": "对象",
        "tab_print": "打印",
        "tab_material": "材料",
        "tab_machine": "机器",
        "tab_preview": "预览",
        "tab_checks": "检查",
        "body_list": "块体列表",
        "edge_list": "边线列表",
        "layer_range": "层范围",
        "layer_min_label": "最小",
        "layer_max_label": "最大",
        "show_travel": "显示空走路径",
        "show_extrusion": "显示挤出路径",
        "show_pose": "显示五轴姿态抽样",
        "feature_legend": "Feature Type 图例",
        "preview_summary": "路径摘要",
        "preview_summary_text": "总路径段 {segments}，当前显示 {visible}；G-code 步骤 {steps}；层范围 {layers}；挤出角色 {roles} 类；旋转轴 {axes}；坐标 {coord}；渲染 {render}",
        "coord_ac_inverse": "AC 反算工件坐标",
        "coord_machine_xyz": "机床 XYZ",
        "coord_machine_xyz_unresolved": "机床 XYZ（旋转轴语义未解析）",
        "segment_property": "路径段属性",
        "segment_property_none": "当前层范围内没有可显示的路径段。",
        "segment_property_text": "步骤 {step} | 行号 {line} | 层 {layer}\n运动类型：{move}\n挤出角色：{role}\n工件起点：{start}\n工件终点：{end}\n机床起点：{machine_start}\n机床终点：{machine_end}\n进给速度：{feedrate}\nE 增量：{delta_e}\n线宽：{width}\n层高：{height}\n旋转轴：{rotary}\n注释来源：{comment}",
        "path_progress": "G-code 进度",
        "progress_empty": "无 G-code 步骤",
        "progress_label_text": "{current}/{total} | {percent:.1f}% | 行 {line} | {move}",
        "progress_prev": "上一步",
        "progress_play": "播放",
        "progress_pause": "暂停",
        "progress_next": "下一步",
        "checks_title": "检查结果",
        "param_layer_bead": "层与道宽",
        "param_layer_height": "层高",
        "param_bead_width": "道宽",
        "param_perimeters": "轮廓道数",
        "param_curve_freeform": "曲线/曲面路径",
        "param_sampling_spacing": "采样间距",
        "param_surface_offset": "曲面偏置",
        "param_toolpath_source": "路径来源",
        "param_material_profile": "材料配置",
        "param_material": "材料",
        "param_nozzle_temp": "喷嘴温度",
        "param_platform_temp": "平台温度",
        "param_extrusion": "挤出",
        "param_extrusion_mode": "挤出模式",
        "param_retraction": "回抽",
        "param_cooling": "冷却",
        "param_machine_profile": "机器配置",
        "param_axis_mapping": "轴名映射",
        "param_nozzle_diameter": "喷嘴直径",
        "param_max_travel_speed": "最大空走速度",
        "param_rotary_limits": "旋转轴限位",
        "param_rotary_metadata": "从导入 G-code 读取 A/C 元数据",
        "status_ready": "就绪",
        "status_loaded": "已载入：{body_count} 个 body，{edge_count} 条 edge",
        "status_single_body": "已载入单实体 STEP；将作为一个制造对象处理",
        "status_gcode_loaded": "已载入 G-code：{segment_count} 个路径段，{layer_count} 层",
        "status_saved": "已保存项目：{path}",
        "status_project_loading": "正在打开项目（{phase}）：{percent:.0f}%",
        "status_project_loaded": "已打开项目：{path}",
        "status_project_load_failed": "打开项目失败：{message}",
        "status_error": "错误：{message}",
        "no_model": "尚未载入模型",
        "no_gcode": "尚未载入 NC/G-code",
        "no_project_content": "尚未载入 STEP 或 NC/G-code",
        "http": "HTTP 自动化：{url}",
        "check_workbench": "工作台：{workbench}",
        "check_no_model": "Warning：尚未载入 STEP 模型，路径可单独预览。",
        "check_model": "STEP 检查：{bodies} 个 body，{edges} 条 edge，可用于对象定义。",
        "check_no_gcode": "Warning：尚未载入 NC/G-code，预览页暂无路径。",
        "check_gcode": "NC 检查：{segments} 个路径段，{layers} 层，旋转轴 {axes}。",
        "check_unknown_roles": "Warning：{count} 个挤出段未能归一到已知 Feature Type。",
        "check_warning_policy": "策略：Warning 可继续预览并写入项目记录；Error 才阻止最终代码输出。",
    },
    "en": {
        "app_title": "5AxisSclicer V2.0 5-Axis Slicing Workbench",
        "workbench_home": "Workbench",
        "manufacturing_setup_entry": "Manufacturing Setup",
        "home_title": "5-axis polymer/resin additive workbenches",
        "home_subtitle": "First use: open STEP → Manufacturing Setup (part, nozzle, material, coordinates) → choose a workbench → generate, inspect and export NC.",
        "load_demo": "Open Impeller Project",
        "gcode_viewer_entry": "Slicing Result Preview",
        "open_step": "Open STEP",
        "open_project": "Open Project",
        "open_gcode": "Open NC/G-code",
        "save": "Save Project",
        "clear": "Clear Selection",
        "fit": "Fit View",
        "home_view": "Home View",
        "language": "中文",
        "operation": "Operation",
        "tube_coordinate_entry": "Enter Tube Setup (Define Coordinates)",
        "operation_imported_nc": "Imported NC Review",
        "operation_curve": "Curve Buildup",
        "operation_freeform": "Freeform Coating",
        "model_file": "STEP Model",
        "gcode_file": "NC/G-code",
        "file_none": "Not loaded",
        "tab_objects": "Objects",
        "tab_print": "Print",
        "tab_material": "Material",
        "tab_machine": "Machine",
        "tab_preview": "Preview",
        "tab_checks": "Checks",
        "body_list": "Bodies",
        "edge_list": "Edges",
        "layer_range": "Layer Range",
        "layer_min_label": "Min",
        "layer_max_label": "Max",
        "show_travel": "Show travel moves",
        "show_extrusion": "Show extrusion moves",
        "show_pose": "Show 5-axis pose samples",
        "feature_legend": "Feature Type Legend",
        "preview_summary": "Toolpath Summary",
        "preview_summary_text": "{segments} total segments, {visible} visible; {steps} G-code steps; layers {layers}; {roles} extrusion roles; rotary axes {axes}; coordinates {coord}; render {render}",
        "coord_ac_inverse": "AC inverse part coordinates",
        "coord_machine_xyz": "Machine XYZ",
        "coord_machine_xyz_unresolved": "Machine XYZ (rotary semantics unresolved)",
        "segment_property": "Segment Properties",
        "segment_property_none": "No visible path segment in the current layer range.",
        "segment_property_text": "Step {step} | Line {line} | Layer {layer}\nMove type: {move}\nExtrusion role: {role}\nPart start: {start}\nPart end: {end}\nMachine start: {machine_start}\nMachine end: {machine_end}\nFeedrate: {feedrate}\nDelta E: {delta_e}\nWidth: {width}\nHeight: {height}\nRotary axes: {rotary}\nComment source: {comment}",
        "path_progress": "G-code Progress",
        "progress_empty": "No G-code steps",
        "progress_label_text": "{current}/{total} | {percent:.1f}% | line {line} | {move}",
        "progress_prev": "Previous step",
        "progress_play": "Play",
        "progress_pause": "Pause",
        "progress_next": "Next step",
        "checks_title": "Checks",
        "param_layer_bead": "Layer and Bead",
        "param_layer_height": "Layer height",
        "param_bead_width": "Bead width",
        "param_perimeters": "Perimeters",
        "param_curve_freeform": "Curve/Freeform",
        "param_sampling_spacing": "Sampling spacing",
        "param_surface_offset": "Surface offset",
        "param_toolpath_source": "Toolpath source",
        "param_material_profile": "Material Profile",
        "param_material": "Material",
        "param_nozzle_temp": "Nozzle temperature",
        "param_platform_temp": "Platform temperature",
        "param_extrusion": "Extrusion",
        "param_extrusion_mode": "Extrusion mode",
        "param_retraction": "Retraction",
        "param_cooling": "Cooling",
        "param_machine_profile": "Machine Profile",
        "param_axis_mapping": "Axis mapping",
        "param_nozzle_diameter": "Nozzle diameter",
        "param_max_travel_speed": "Max travel speed",
        "param_rotary_limits": "Rotary limits",
        "param_rotary_metadata": "A/C metadata from imported G-code",
        "status_ready": "Ready",
        "status_loaded": "Loaded {body_count} bodies and {edge_count} edges",
        "status_single_body": "Single-solid STEP loaded; it will be handled as one manufacturing object",
        "status_gcode_loaded": "Loaded G-code: {segment_count} segments, {layer_count} layers",
        "status_saved": "Project saved: {path}",
        "status_project_loading": "Opening project ({phase}): {percent:.0f}%",
        "status_project_loaded": "Project opened: {path}",
        "status_project_load_failed": "Could not open project: {message}",
        "status_error": "Error: {message}",
        "no_model": "No model loaded",
        "no_gcode": "No NC/G-code loaded",
        "no_project_content": "No STEP or NC/G-code loaded",
        "http": "HTTP automation: {url}",
        "check_workbench": "Workbench: {workbench}",
        "check_no_model": "Warning: no STEP model is loaded; the imported path can still be previewed.",
        "check_model": "STEP check: {bodies} bodies and {edges} edges are available for object definition.",
        "check_no_gcode": "Warning: no NC/G-code is loaded; the preview has no path yet.",
        "check_gcode": "NC check: {segments} path segments, {layers} layers, rotary axes {axes}.",
        "check_unknown_roles": "Warning: {count} extrusion segments could not be mapped to a known Feature Type.",
        "check_warning_policy": "Policy: warnings remain previewable and are saved; errors block final code output.",
    },
}


_RESULT_PREVIEW_TRANSLATIONS: dict[str, dict[str, str]] = {
    "zh": {
        "menu_file": "文件",
        "menu_model": "模型",
        "menu_slice": "切片",
        "menu_preview": "预览",
        "menu_gcode": "G-code",
        "menu_tools": "工具",
        "menu_help": "帮助",
        "action_load_impeller_demo": "打开叶轮项目",
        "action_open_step": "打开 STEP…",
        "action_open_gcode": "打开现有 G-code…",
        "action_save_project": "保存项目…",
        "action_exit": "退出",
        "action_show_model": "显示模型",
        "action_hide_model": "隐藏模型",
        "action_slice_and_preview": "解析 G-code",
        "action_open_result_preview": "切片成果预览",
        "action_cancel_loading": "取消加载",
        "action_fit_view": "适配视图",
        "action_home_view": "初始视角",
        "action_view_isometric": "等轴测视图",
        "action_view_front": "前视图",
        "action_view_back": "后视图",
        "action_view_left": "左视图",
        "action_view_right": "右视图",
        "action_view_top": "俯视图",
        "action_view_bottom": "仰视图",
        "action_toggle_model": "模型显隐",
        "action_toggle_extrusion": "挤出路径显隐",
        "action_toggle_start_end": "起终点显隐",
        "action_toggle_part_axes": "Part XYZ 轴标显隐",
        "action_toggle_orientation_cube": "方向立方体显隐",
        "action_toggle_travel": "空走路径显隐",
        "action_toggle_pose": "姿态抽样显隐",
        "action_quality_interactive": "交互质量",
        "action_quality_paper": "完整路径",
        "action_search_gcode": "搜索代码…",
        "action_jump_to_line": "跳转到行…",
        "action_language_chinese": "中文",
        "action_language_english": "English",
        "action_user_guide": "使用帮助",
        "action_about": "关于 5AxisSclicer",
        "result_preview_title": "切片成果预览",
        "result_preview_subtitle": "五轴路径检查、统计与代码定位",
        "result_back_to_workbench": "返回工作台",
        "result_column_sources": "输入与参数",
        "result_column_viewer": "三维成果",
        "result_column_analysis": "统计与代码",
        "result_current_source": "输入文件",
        "result_model_source": "STEP 模型",
        "result_gcode_source": "G-code 路径",
        "result_source_not_loaded": "未加载",
        "result_source_browse": "浏览…",
        "result_remove_source": "移除来源",
        "result_load_impeller_demo": "打开叶轮项目",
        "result_open_existing_gcode": "打开 G-code",
        "result_open_step": "打开 STEP",
        "result_slice_and_preview": "解析 G-code",
        "result_state": "成果状态",
        "result_state_empty": "空白",
        "result_state_empty_detail": "打开项目或选择 G-code、STEP 文件。",
        "result_state_loading": "正在加载",
        "result_state_loading_detail": "正在解析源文件并构建三维路径。",
        "result_state_ready": "已就绪",
        "result_state_ready_detail": "模型、路径与代码索引已加载。",
        "result_state_warning": "警告",
        "result_state_warning_detail": "成果可继续查看，请核对右栏提示。",
        "result_state_error": "错误",
        "result_state_error_detail": "加载失败，上一份有效场景已保留。",
        "result_loading_progress": "{percent:.1f}% · {phase}",
        "result_cancel_requested": "正在安全取消…",
        "result_previous_scene_retained": "已保留上一份有效场景",
        "result_stale_load_ignored": "已忽略过期加载结果",
        "process_parameters": "工艺参数",
        "parameter_layer_height": "层高",
        "parameter_print_speed": "打印速度",
        "parameter_extrusion_width": "挤出宽度",
        "parameter_nozzle_diameter": "喷嘴直径",
        "parameter_process_mode": "路径模式",
        "parameter_process_mode_shell": "Shell",
        "parameter_top_bottom_layers": "顶底层",
        "parameter_value_mm": "{value:.2f} mm",
        "parameter_value_mm_per_min": "{value:.0f} mm/min",
        "parameter_value_layers": "{value} 层",
        "parameter_edit": "编辑",
        "parameter_save": "保存",
        "parameter_reset": "重置",
        "parameter_saved": "工艺参数已保存",
        "parameter_invalid": "请检查参数范围和数值格式。",
        "view_tools": "视图工具",
        "view_orientation_cube": "方向立方体",
        "view_part_axes": "Part XYZ",
        "view_start_point": "起点",
        "view_end_point": "终点",
        "view_build_plate": "平面底座",
        "stage_navigation": "阶段导航",
        "stage_all": "全部",
        "stage_base": "底座",
        "stage_blade_1": "叶片 1",
        "stage_blade_2": "叶片 2",
        "stage_blade_3": "叶片 3",
        "stage_blade_4": "叶片 4",
        "stage_blade_5": "叶片 5",
        "stage_blade_6": "叶片 6",
        "stage_blade_7": "叶片 7",
        "stage_blade_8": "叶片 8",
        "stage_layer_range": "层 {start}–{end}",
        "stage_marker_fallback": "源文件未包含叶轮阶段标记，当前按全部路径与层范围导航。",
        "result_progress": "路径进度",
        "result_progress_previous": "上一个阶段",
        "result_progress_play": "播放进度",
        "result_progress_pause": "暂停进度",
        "result_progress_next": "下一个阶段",
        "quality_mode": "质量模式",
        "quality_interactive": "交互质量",
        "quality_paper": "完整路径",
        "result_summary": "路径统计",
        "result_thumbnail": "全局等轴测缩略图",
        "result_thumbnail_fixed_camera": "固定相机，不随主视图联动",
        "statistics_geometry": "模型几何",
        "statistics_toolpath": "路径数据",
        "statistics_bodies": "Body",
        "statistics_edges": "Edge",
        "statistics_base_layers": "底座层",
        "statistics_blade_stages": "叶片阶段",
        "statistics_spatial_segments": "空间段",
        "statistics_extrusion_segments": "正挤出段",
        "statistics_travel_segments": "空走或非挤出段",
        "statistics_layer_range": "层范围",
        "statistics_a_range": "A 轴范围",
        "statistics_c_range": "C 轴范围",
        "statistics_coordinate_reconstruction": "工件坐标反算",
        "statistics_coordinate_formula": "P_part = Rz(-C) × Rx(-A) × P_machine",
        "statistics_continuity_tolerance": "Polyline 连续性容差",
        "statistics_actual_data": "数据源：当前 G-code",
        "statistics_unavailable": "暂无数据",
        "visibility_title": "场景显隐",
        "visibility_model": "模型",
        "visibility_extrusion": "正挤出路径",
        "visibility_travel": "空走路径",
        "visibility_pose": "姿态抽样",
        "visibility_start_end": "起点与终点",
        "visibility_part_axes": "Part XYZ 轴标",
        "visibility_orientation_cube": "方向立方体",
        "legend_model": "模型表面",
        "legend_extrusion": "正挤出路径",
        "legend_start": "起点",
        "legend_end": "终点",
        "gcode_context": "G-code 上下文",
        "gcode_current_line": "当前行 {line}",
        "gcode_line_count": "共 {count} 行",
        "gcode_window_range": "显示第 {start}–{end} 行",
        "gcode_search": "搜索",
        "gcode_search_placeholder": "输入指令、坐标或注释",
        "gcode_search_previous": "上一个匹配项",
        "gcode_search_next": "下一个匹配项",
        "gcode_searching": "正在异步搜索…",
        "gcode_no_matches": "未找到匹配项",
        "gcode_match_count": "第 {current} 项，共 {total} 项",
        "gcode_jump": "跳转",
        "gcode_jump_placeholder": "行号",
        "gcode_jump_go": "转到",
        "gcode_line_out_of_range": "行号应位于 1 至 {maximum}。",
        "gcode_syntax_legend": "语法颜色",
        "gcode_syntax_feedrate": "F 进给速度",
        "gcode_syntax_xyz": "XYZ 直线轴",
        "gcode_syntax_ac": "A/C 回转轴",
        "gcode_syntax_extrusion": "E 挤出量",
        "dialog_open_step_title": "选择 STEP 模型",
        "dialog_open_gcode_title": "选择 G-code 文件",
        "dialog_save_project_title": "选择项目保存目录",
        "dialog_cancel_loading_title": "取消当前加载",
        "dialog_cancel_loading_message": "已提交取消请求，当前有效场景会继续保留。",
        "dialog_overwrite_title": "确认覆盖",
        "dialog_overwrite_message": "输出目录中存在同名文件，是否覆盖？",
        "dialog_error_title": "操作失败",
        "dialog_warning_title": "需要核对",
        "dialog_information_title": "操作完成",
        "file_filter_step": "STEP 模型 (*.step *.stp)",
        "file_filter_gcode": "G-code 文件 (*.gcode *.nc *.tap *.txt)",
        "file_filter_project": "5AxisSclicer 项目 (project.json)",
        "file_filter_png": "PNG 图像 (*.png)",
        "tooltip_load_demo": "打开内置叶轮 STEP 与完整 G-code 项目",
        "tooltip_open_step": "选择 STEP/STP 模型作为成果几何来源",
        "tooltip_open_gcode": "选择已有 G-code/NC 文件并在后台解析",
        "tooltip_slice_preview": "解析当前 G-code，反算工件坐标并构建预览缓存",
        "tooltip_cancel_loading": "请求后台任务在安全检查点停止",
        "tooltip_fit_view": "将当前可见场景适配到视窗",
        "tooltip_home_view": "恢复成果页默认全局等轴测视角",
        "tooltip_orientation_cube": "单击立方体表面切换六个标准方向",
        "tooltip_quality_mode": "切换交互 LOD 与完整路径渲染",
        "tooltip_stage_navigation": "按底座、叶片阶段或层范围筛选进度",
        "tooltip_progress": "拖动或播放当前路径构建进度",
        "tooltip_visibility_model": "显示或隐藏灰色 STEP 模型",
        "tooltip_visibility_extrusion": "显示或隐藏蓝色正挤出路径",
        "tooltip_visibility_start_end": "显示或隐藏绿色起点与红色终点",
        "tooltip_visibility_axes": "显示或隐藏 Part XYZ 轴标",
        "tooltip_gcode_search": "在 mmap 行索引上异步搜索源代码",
        "tooltip_gcode_jump": "跳转到真实源文件行号",
        "tooltip_parameter_edit": "编辑项目工艺参数",
        "tooltip_parameter_save": "保存项目工艺参数",
        "tooltip_parameter_reset": "恢复默认工艺参数",
        "tooltip_language": "切换全局界面语言",
        "tooltip_help": "查看成果页操作和数据口径",
        "error_file_not_found": "文件不存在：{path}",
        "error_file_unreadable": "无法读取文件：{path}",
        "error_unsupported_file": "不支持的文件格式：{suffix}",
        "error_invalid_gcode": "未识别到可用的 G-code 运动指令。",
        "error_load_cancelled": "加载已取消",
        "error_load_failed": "加载失败：{message}",
        "status_waiting_for_loader_shutdown": "正在等待后台文件读取安全结束…",
        "error_render_unavailable": "当前渲染后端不支持离屏画面捕获。",
    },
    "en": {
        "menu_file": "File",
        "menu_model": "Model",
        "menu_slice": "Slice",
        "menu_preview": "Preview",
        "menu_gcode": "G-code",
        "menu_tools": "Tools",
        "menu_help": "Help",
        "action_load_impeller_demo": "Open Impeller Project",
        "action_open_step": "Open STEP…",
        "action_open_gcode": "Open Existing G-code…",
        "action_save_project": "Save Project…",
        "action_exit": "Exit",
        "action_show_model": "Show Model",
        "action_hide_model": "Hide Model",
        "action_slice_and_preview": "Parse G-code",
        "action_open_result_preview": "Result Preview",
        "action_cancel_loading": "Cancel Loading",
        "action_fit_view": "Fit View",
        "action_home_view": "Home View",
        "action_view_isometric": "Isometric View",
        "action_view_front": "Front View",
        "action_view_back": "Back View",
        "action_view_left": "Left View",
        "action_view_right": "Right View",
        "action_view_top": "Top View",
        "action_view_bottom": "Bottom View",
        "action_toggle_model": "Toggle Model",
        "action_toggle_extrusion": "Toggle Extrusion Path",
        "action_toggle_start_end": "Toggle Start and End Points",
        "action_toggle_part_axes": "Toggle Part XYZ Axes",
        "action_toggle_orientation_cube": "Toggle Orientation Cube",
        "action_toggle_travel": "Toggle Travel Path",
        "action_toggle_pose": "Toggle Pose Samples",
        "action_quality_interactive": "Interactive Quality",
        "action_quality_paper": "Full Path",
        "action_search_gcode": "Search Code…",
        "action_jump_to_line": "Jump to Line…",
        "action_language_chinese": "中文",
        "action_language_english": "English",
        "action_user_guide": "User Guide",
        "action_about": "About 5AxisSclicer",
        "result_preview_title": "Slicing Result Preview",
        "result_preview_subtitle": "Five-axis path inspection, statistics, and G-code navigation",
        "result_back_to_workbench": "Back to Workbench",
        "result_column_sources": "Inputs & Parameters",
        "result_column_viewer": "3D Result",
        "result_column_analysis": "Statistics and Code",
        "result_current_source": "Input Files",
        "result_model_source": "STEP Model",
        "result_gcode_source": "G-code Path",
        "result_source_not_loaded": "Not loaded",
        "result_source_browse": "Browse…",
        "result_remove_source": "Remove Source",
        "result_load_impeller_demo": "Open Impeller",
        "result_open_existing_gcode": "Open G-code",
        "result_open_step": "Open STEP",
        "result_slice_and_preview": "Parse G-code",
        "result_state": "Result Status",
        "result_state_empty": "Empty",
        "result_state_empty_detail": "Open a project, G-code, or STEP file.",
        "result_state_loading": "Loading",
        "result_state_loading_detail": "Parsing source files and building the 3D toolpath.",
        "result_state_ready": "Ready",
        "result_state_ready_detail": "The model, toolpath, and code index are loaded.",
        "result_state_warning": "Warning",
        "result_state_warning_detail": "The result remains available; review the notice in the right column.",
        "result_state_error": "Error",
        "result_state_error_detail": "Loading failed; the previous valid scene was retained.",
        "result_loading_progress": "{percent:.1f}% · {phase}",
        "result_cancel_requested": "Cancelling safely…",
        "result_previous_scene_retained": "Previous valid scene retained",
        "result_stale_load_ignored": "Stale load result ignored",
        "process_parameters": "Process Parameters",
        "parameter_layer_height": "Layer height",
        "parameter_print_speed": "Print speed",
        "parameter_extrusion_width": "Extrusion width",
        "parameter_nozzle_diameter": "Nozzle diameter",
        "parameter_process_mode": "Path mode",
        "parameter_process_mode_shell": "Shell",
        "parameter_top_bottom_layers": "Top/bottom layers",
        "parameter_value_mm": "{value:.2f} mm",
        "parameter_value_mm_per_min": "{value:.0f} mm/min",
        "parameter_value_layers": "{value} layers",
        "parameter_edit": "Edit",
        "parameter_save": "Save",
        "parameter_reset": "Reset",
        "parameter_saved": "Process parameters saved",
        "parameter_invalid": "Check the parameter ranges and number formats.",
        "view_tools": "View Tools",
        "view_orientation_cube": "Orientation Cube",
        "view_part_axes": "Part XYZ",
        "view_start_point": "Start",
        "view_end_point": "End",
        "view_build_plate": "Build Plate",
        "stage_navigation": "Stage Navigation",
        "stage_all": "All",
        "stage_base": "Base",
        "stage_blade_1": "Blade 1",
        "stage_blade_2": "Blade 2",
        "stage_blade_3": "Blade 3",
        "stage_blade_4": "Blade 4",
        "stage_blade_5": "Blade 5",
        "stage_blade_6": "Blade 6",
        "stage_blade_7": "Blade 7",
        "stage_blade_8": "Blade 8",
        "stage_layer_range": "Layers {start}–{end}",
        "stage_marker_fallback": "No impeller stage markers were found; navigation uses All and layer ranges.",
        "result_progress": "Path Progress",
        "result_progress_previous": "Previous Stage",
        "result_progress_play": "Play Progress",
        "result_progress_pause": "Pause Progress",
        "result_progress_next": "Next Stage",
        "quality_mode": "Quality Mode",
        "quality_interactive": "Interactive",
        "quality_paper": "Full Path",
        "result_summary": "Toolpath Statistics",
        "result_thumbnail": "Global Isometric Thumbnail",
        "result_thumbnail_fixed_camera": "Fixed camera, independent of the main view",
        "statistics_geometry": "Model Geometry",
        "statistics_toolpath": "Toolpath Data",
        "statistics_bodies": "Bodies",
        "statistics_edges": "Edges",
        "statistics_base_layers": "Base layers",
        "statistics_blade_stages": "Blade stages",
        "statistics_spatial_segments": "Spatial segments",
        "statistics_extrusion_segments": "Positive-extrusion segments",
        "statistics_travel_segments": "Travel or non-extrusion segments",
        "statistics_layer_range": "Layer range",
        "statistics_a_range": "A-axis range",
        "statistics_c_range": "C-axis range",
        "statistics_coordinate_reconstruction": "Part-coordinate reconstruction",
        "statistics_coordinate_formula": "P_part = Rz(-C) × Rx(-A) × P_machine",
        "statistics_continuity_tolerance": "Polyline continuity tolerance",
        "statistics_actual_data": "Data source: current G-code",
        "statistics_unavailable": "No data",
        "visibility_title": "Scene Visibility",
        "visibility_model": "Model",
        "visibility_extrusion": "Extrusion Path",
        "visibility_travel": "Travel path",
        "visibility_pose": "Pose samples",
        "visibility_start_end": "Start / End Points",
        "visibility_part_axes": "Part XYZ axes",
        "visibility_orientation_cube": "Orientation cube",
        "legend_model": "Model surface",
        "legend_extrusion": "Positive-extrusion path",
        "legend_start": "Start",
        "legend_end": "End",
        "gcode_context": "G-code Context",
        "gcode_current_line": "Current line {line}",
        "gcode_line_count": "{count} lines",
        "gcode_window_range": "Showing lines {start}–{end}",
        "gcode_search": "Search",
        "gcode_search_placeholder": "Enter an instruction, coordinate, or comment",
        "gcode_search_previous": "Previous Match",
        "gcode_search_next": "Next Match",
        "gcode_searching": "Searching asynchronously…",
        "gcode_no_matches": "No matches found",
        "gcode_match_count": "Match {current} of {total}",
        "gcode_jump": "Jump",
        "gcode_jump_placeholder": "Line number",
        "gcode_jump_go": "Go",
        "gcode_line_out_of_range": "Enter a line number from 1 to {maximum}.",
        "gcode_syntax_legend": "Syntax Colors",
        "gcode_syntax_feedrate": "F feedrate",
        "gcode_syntax_xyz": "XYZ linear axes",
        "gcode_syntax_ac": "A/C rotary axes",
        "gcode_syntax_extrusion": "E extrusion",
        "dialog_open_step_title": "Select STEP Model",
        "dialog_open_gcode_title": "Select G-code File",
        "dialog_save_project_title": "Select Project Folder",
        "dialog_cancel_loading_title": "Cancel Current Load",
        "dialog_cancel_loading_message": "The cancellation request was submitted; the current valid scene will remain available.",
        "dialog_overwrite_title": "Confirm Overwrite",
        "dialog_overwrite_message": "Files with the same names already exist in the output folder. Overwrite them?",
        "dialog_error_title": "Operation Failed",
        "dialog_warning_title": "Review Required",
        "dialog_information_title": "Operation Complete",
        "file_filter_step": "STEP Models (*.step *.stp)",
        "file_filter_gcode": "G-code Files (*.gcode *.nc *.tap *.txt)",
        "file_filter_project": "5AxisSclicer Project (project.json)",
        "file_filter_png": "PNG Images (*.png)",
        "tooltip_load_demo": "Open the built-in impeller STEP and complete G-code project",
        "tooltip_open_step": "Choose a STEP/STP model as the result geometry source",
        "tooltip_open_gcode": "Choose an existing G-code/NC file and parse it in the background",
        "tooltip_slice_preview": "Parse the current G-code, reconstruct part coordinates, and build the preview cache",
        "tooltip_cancel_loading": "Ask the background task to stop at a safe checkpoint",
        "tooltip_fit_view": "Fit the currently visible scene to the viewport",
        "tooltip_home_view": "Restore the result page's default global isometric view",
        "tooltip_orientation_cube": "Click a cube face to select one of six standard directions",
        "tooltip_quality_mode": "Switch between interactive LOD and full-path rendering",
        "tooltip_stage_navigation": "Filter progress by the base, a blade stage, or a layer range",
        "tooltip_progress": "Scrub or play the current path construction progress",
        "tooltip_visibility_model": "Show or hide the gray STEP model",
        "tooltip_visibility_extrusion": "Show or hide the blue positive-extrusion path",
        "tooltip_visibility_start_end": "Show or hide the green start and red end markers",
        "tooltip_visibility_axes": "Show or hide the Part XYZ axes",
        "tooltip_gcode_search": "Search the source asynchronously using its mmap line index",
        "tooltip_gcode_jump": "Jump to a real source-file line number",
        "tooltip_parameter_edit": "Edit the project process parameters",
        "tooltip_parameter_save": "Save the project process parameters",
        "tooltip_parameter_reset": "Restore the default process parameters",
        "tooltip_language": "Switch the global interface language",
        "tooltip_help": "Review result-page controls and data conventions",
        "error_file_not_found": "File not found: {path}",
        "error_file_unreadable": "Cannot read file: {path}",
        "error_unsupported_file": "Unsupported file format: {suffix}",
        "error_invalid_gcode": "No usable G-code motion instruction was found.",
        "error_load_cancelled": "Loading cancelled",
        "error_load_failed": "Loading failed: {message}",
        "status_waiting_for_loader_shutdown": "Waiting for the background file reader to stop safely…",
        "error_render_unavailable": "The current render backend does not support offscreen capture.",
    },
}

for _language, _catalog in _RESULT_PREVIEW_TRANSLATIONS.items():
    TRANSLATIONS[_language].update(_catalog)


def tr(language: str, key: str, **kwargs: object) -> str:
    text = TRANSLATIONS.get(language, TRANSLATIONS["zh"]).get(key, key)
    return text.format(**kwargs)
