from __future__ import annotations


TRANSLATIONS: dict[str, dict[str, str]] = {
    "zh": {
        "app_title": "5AxisSclicer V2.0 论文预览工作台",
        "workbench_home": "工作台",
        "home_title": "五轴塑料/树脂增材工作台",
        "home_subtitle": "选择增材处理类型后进入 Operation Session，完成制造对象定义、参数设置、NC 路径预览和检查。",
        "load_demo": "载入扇叶演示",
        "open_step": "打开 STEP",
        "open_gcode": "打开 NC/G-code",
        "save": "保存项目",
        "clear": "清空选择",
        "fit": "适配视图",
        "home_view": "初始视角",
        "language": "English",
        "operation": "操作类型",
        "operation_imported_nc": "Imported NC Review（导入路径检查）",
        "operation_curve": "Curve Buildup（预览）",
        "operation_freeform": "Freeform Coating（预览）",
        "model_file": "STEP 模型",
        "gcode_file": "NC/G-code",
        "file_none": "未载入",
        "tab_objects": "对象",
        "tab_print": "打印",
        "tab_material": "材料",
        "tab_machine": "机器",
        "tab_preview": "预览",
        "tab_checks": "检查",
        "body_list": "块体列表",
        "edge_list": "边线列表",
        "layer_range": "层范围",
        "layer_min_label": "最小",
        "layer_max_label": "最大",
        "show_travel": "显示空走路径",
        "show_extrusion": "显示挤出路径",
        "show_pose": "显示五轴姿态抽样",
        "feature_legend": "Feature Type 图例",
        "preview_summary": "路径摘要",
        "preview_summary_text": "总路径段 {segments}，当前显示 {visible}；层范围 {layers}；挤出角色 {roles} 类；旋转轴 {axes}",
        "segment_property": "路径段属性",
        "segment_property_none": "当前层范围内没有可显示的路径段。",
        "segment_property_text": "行号 {line} | 层 {layer}\n运动类型：{move}\n挤出角色：{role}\n起点：{start}\n终点：{end}\n进给速度：{feedrate}\nE 增量：{delta_e}\n线宽：{width}\n旋转轴：{rotary}\n注释来源：{comment}",
        "checks_title": "检查结果",
        "param_layer_bead": "层与道宽",
        "param_layer_height": "层高",
        "param_bead_width": "道宽",
        "param_perimeters": "轮廓道数",
        "param_curve_freeform": "曲线/曲面路径",
        "param_sampling_spacing": "采样间距",
        "param_surface_offset": "曲面偏置",
        "param_toolpath_source": "路径来源",
        "param_material_profile": "材料配置",
        "param_material": "材料",
        "param_nozzle_temp": "喷嘴温度",
        "param_platform_temp": "平台温度",
        "param_extrusion": "挤出",
        "param_extrusion_mode": "挤出模式",
        "param_retraction": "回抽",
        "param_cooling": "冷却",
        "param_machine_profile": "机器配置",
        "param_axis_mapping": "轴名映射",
        "param_nozzle_diameter": "喷嘴直径",
        "param_max_travel_speed": "最大空走速度",
        "param_rotary_limits": "旋转轴限位",
        "param_rotary_metadata": "从导入 G-code 读取 A/C 元数据",
        "status_ready": "就绪",
        "status_loaded": "已载入：{body_count} 个 body，{edge_count} 条 edge",
        "status_single_body": "已载入单实体 STEP；首版不做区域自动识别",
        "status_gcode_loaded": "已载入 G-code：{segment_count} 个路径段，{layer_count} 层",
        "status_saved": "已保存项目：{path}",
        "status_error": "错误：{message}",
        "no_model": "尚未载入模型",
        "no_gcode": "尚未载入 NC/G-code",
        "no_project_content": "尚未载入 STEP 或 NC/G-code",
        "http": "HTTP 自动化：{url}",
        "check_workbench": "工作台：{workbench}",
        "check_no_model": "Warning：尚未载入 STEP 模型，路径可单独预览。",
        "check_model": "STEP 检查：{bodies} 个 body，{edges} 条 edge，可用于对象定义。",
        "check_no_gcode": "Warning：尚未载入 NC/G-code，预览页暂无路径。",
        "check_gcode": "NC 检查：{segments} 个路径段，{layers} 层，旋转轴 {axes}。",
        "check_unknown_roles": "Warning：{count} 个挤出段未能归一到已知 Feature Type。",
        "check_warning_policy": "策略：Warning 可继续预览并写入项目记录；Error 才阻止最终代码输出。",
    },
    "en": {
        "app_title": "5AxisSclicer V2.0 Thesis Preview Workbench",
        "workbench_home": "Workbench",
        "home_title": "5-axis polymer/resin additive workbenches",
        "home_subtitle": "Select an additive process type, then enter an Operation Session for object definition, parameters, NC preview, and checks.",
        "load_demo": "Load fan blade demo",
        "open_step": "Open STEP",
        "open_gcode": "Open NC/G-code",
        "save": "Save Project",
        "clear": "Clear Selection",
        "fit": "Fit View",
        "home_view": "Home View",
        "language": "中文",
        "operation": "Operation",
        "operation_imported_nc": "Imported NC Review",
        "operation_curve": "Curve Buildup (Preview)",
        "operation_freeform": "Freeform Coating (Preview)",
        "model_file": "STEP Model",
        "gcode_file": "NC/G-code",
        "file_none": "Not loaded",
        "tab_objects": "Objects",
        "tab_print": "Print",
        "tab_material": "Material",
        "tab_machine": "Machine",
        "tab_preview": "Preview",
        "tab_checks": "Checks",
        "body_list": "Bodies",
        "edge_list": "Edges",
        "layer_range": "Layer Range",
        "layer_min_label": "Min",
        "layer_max_label": "Max",
        "show_travel": "Show travel moves",
        "show_extrusion": "Show extrusion moves",
        "show_pose": "Show 5-axis pose samples",
        "feature_legend": "Feature Type Legend",
        "preview_summary": "Toolpath Summary",
        "preview_summary_text": "{segments} total segments, {visible} visible; layers {layers}; {roles} extrusion roles; rotary axes {axes}",
        "segment_property": "Segment Properties",
        "segment_property_none": "No visible path segment in the current layer range.",
        "segment_property_text": "Line {line} | Layer {layer}\nMove type: {move}\nExtrusion role: {role}\nStart: {start}\nEnd: {end}\nFeedrate: {feedrate}\nDelta E: {delta_e}\nWidth: {width}\nRotary axes: {rotary}\nComment source: {comment}",
        "checks_title": "Checks",
        "param_layer_bead": "Layer and Bead",
        "param_layer_height": "Layer height",
        "param_bead_width": "Bead width",
        "param_perimeters": "Perimeters",
        "param_curve_freeform": "Curve/Freeform",
        "param_sampling_spacing": "Sampling spacing",
        "param_surface_offset": "Surface offset",
        "param_toolpath_source": "Toolpath source",
        "param_material_profile": "Material Profile",
        "param_material": "Material",
        "param_nozzle_temp": "Nozzle temperature",
        "param_platform_temp": "Platform temperature",
        "param_extrusion": "Extrusion",
        "param_extrusion_mode": "Extrusion mode",
        "param_retraction": "Retraction",
        "param_cooling": "Cooling",
        "param_machine_profile": "Machine Profile",
        "param_axis_mapping": "Axis mapping",
        "param_nozzle_diameter": "Nozzle diameter",
        "param_max_travel_speed": "Max travel speed",
        "param_rotary_limits": "Rotary limits",
        "param_rotary_metadata": "A/C metadata from imported G-code",
        "status_ready": "Ready",
        "status_loaded": "Loaded {body_count} bodies and {edge_count} edges",
        "status_single_body": "Single-solid STEP loaded; automatic region detection is out of scope",
        "status_gcode_loaded": "Loaded G-code: {segment_count} segments, {layer_count} layers",
        "status_saved": "Project saved: {path}",
        "status_error": "Error: {message}",
        "no_model": "No model loaded",
        "no_gcode": "No NC/G-code loaded",
        "no_project_content": "No STEP or NC/G-code loaded",
        "http": "HTTP automation: {url}",
        "check_workbench": "Workbench: {workbench}",
        "check_no_model": "Warning: no STEP model is loaded; the imported path can still be previewed.",
        "check_model": "STEP check: {bodies} bodies and {edges} edges are available for object definition.",
        "check_no_gcode": "Warning: no NC/G-code is loaded; the preview has no path yet.",
        "check_gcode": "NC check: {segments} path segments, {layers} layers, rotary axes {axes}.",
        "check_unknown_roles": "Warning: {count} extrusion segments could not be mapped to a known Feature Type.",
        "check_warning_policy": "Policy: warnings remain previewable and are saved; errors block final code output.",
    },
}


def tr(language: str, key: str, **kwargs: object) -> str:
    text = TRANSLATIONS.get(language, TRANSLATIONS["zh"]).get(key, key)
    return text.format(**kwargs)
