"""Tube Setup labels and the coordinate-entry order shared by Qt shells."""

from __future__ import annotations

from collections.abc import Mapping

from .manufacturing.setup import (
    BUILD_CS_NODE,
    MACHINE_NODE,
    MATERIAL_NODE,
    MODEL_CS_NODE,
    NOZZLE_NODE,
    PART_NODE,
    PLACEMENT_NODE,
    NodeState,
    SetupValidationReport,
)

TUBE_TEXT: dict[str, dict[str, str]] = {
    "zh": {
        "title": "管状工作台",
        "subtitle": "管状薄壁分块定向切片：制造 Setup 与坐标闭环",
        "back": "工作台",
        "open": "打开 STEP",
        "update_source": "从原文件更新",
        "save": "保存项目",
        "create_operation": "创建 Tube Thin-Wall Indexed",
        "project": "项目",
        "model": "模型",
        "setup": "制造设置 1",
        "operations": "操作",
        "part": "零件（Part）",
        "machine": "机床（Machine）",
        "nozzle": "喷嘴",
        "material": "材料",
        "model_cs": "模型坐标系（Model CS）",
        "build_cs": "构建坐标系（Build CS）",
        "placement": "装夹定位（Placement）",
        "operation": "Tube Thin-Wall Indexed",
        "model_view": "模型视图",
        "machine_view": "机床视图",
        "editor_empty": "从左侧树选择 Setup 节点。",
        "part_help": "一个 Part 可包含多个封闭 solid；未分配和 Ignore 不参与后续计算。",
        "body": "实体",
        "kind": "类型",
        "role": "角色",
        "role_part": "零件",
        "role_ignore": "忽略",
        "role_unassigned": "未分配",
        "confirm": "确认",
        "apply": "应用",
        "cancel": "取消",
        "flip": "翻转",
        "resource_help": "内置资源是只读模板，项目保存冻结快照。",
        "resource_origin_builtin": "内置",
        "resource_origin_user": "用户库",
        "resource_origin_snapshot": "项目快照",
        "resource_status_diverged": "已分叉",
        "resource_status_missing": "库中缺失",
        "select_machine": "选择 Machine Profile",
        "select_nozzle": "选择喷嘴身份模板",
        "select_material": "选择 Cura 材料模板",
        "interface": "安装接口",
        "length": "总长 (mm)",
        "collision_profile": "生成临时轴对称碰撞外形",
        "review": "已核对来源中的材料单点建议值",
        "coordinate_help_model": "数值输入基于 Source CS。原点、Z 和 X 需要逐项确认。",
        "coordinate_help_build": "数值输入默认基于 Model CS，保存时换算到 Source CS。",
        "origin": "原点",
        "z_direction": "Z方向",
        "x_direction": "X方向",
        "pick": "拾取",
        "numeric": "数值输入",
        "pick_vertex": "拾取顶点",
        "pick_face": "拾取面上点",
        "pick_line": "拾取直边",
        "pick_axis_face": "拾取平面/圆柱/圆锥面",
        "pick_two_vertices": "拾取两个顶点",
        "placement_help": "Build CS 与打印板安装位配对；微调顺序为平移、Rx、Ry、Rz。",
        "mount": "打印板安装位",
        "coordinates_valid": "坐标有效",
        "setup_ready": "设置就绪",
        "issues": "问题列表",
        "no_issues": "当前没有问题。",
        "ready_warning": "就绪（有警告）",
        "status_missing": "缺失",
        "status_draft": "草稿",
        "status_valid": "有效",
        "status_dirty": "待更新",
        "status_invalid": "无效",
    },
    "en": {
        "title": "Tube Workbench",
        "subtitle": "Indexed tube thin-wall slicing: manufacturing Setup and coordinate closure",
        "back": "Workbench",
        "open": "Open STEP",
        "update_source": "Update from Source",
        "save": "Save Project",
        "create_operation": "Create Tube Thin-Wall Indexed",
        "project": "Project",
        "model": "Model",
        "setup": "Manufacturing Setup 1",
        "operations": "Operations",
        "part": "Part",
        "machine": "Machine",
        "nozzle": "Nozzle",
        "material": "Material",
        "model_cs": "Model CS",
        "build_cs": "Build CS",
        "placement": "Placement",
        "operation": "Tube Thin-Wall Indexed",
        "model_view": "Model View",
        "machine_view": "Machine View",
        "editor_empty": "Select a Setup node in the tree.",
        "part_help": "One Part may contain several closed solids. Unassigned and Ignore bodies are excluded.",
        "body": "Body",
        "kind": "Kind",
        "role": "Role",
        "role_part": "Part",
        "role_ignore": "Ignore",
        "role_unassigned": "Unassigned",
        "confirm": "Confirm",
        "apply": "Apply",
        "cancel": "Cancel",
        "flip": "Flip",
        "resource_help": "Built-in resources are read-only templates; projects store frozen snapshots.",
        "resource_origin_builtin": "Built-in",
        "resource_origin_user": "User library",
        "resource_origin_snapshot": "Project snapshot",
        "resource_status_diverged": "Diverged",
        "resource_status_missing": "Missing from library",
        "select_machine": "Select Machine Profile",
        "select_nozzle": "Select nozzle identity template",
        "select_material": "Select Cura material template",
        "interface": "Mount interface",
        "length": "Overall length (mm)",
        "collision_profile": "Create a temporary axisymmetric collision envelope",
        "review": "Pinned material recommendations reviewed",
        "coordinate_help_model": "Numeric values use Source CS. Confirm origin, Z, and X separately.",
        "coordinate_help_build": "Numeric values use Model CS by default and are persisted in Source CS.",
        "origin": "Origin",
        "z_direction": "Z direction",
        "x_direction": "X direction",
        "pick": "Pick",
        "numeric": "Numeric",
        "pick_vertex": "Pick vertex",
        "pick_face": "Pick point on face",
        "pick_line": "Pick straight edge",
        "pick_axis_face": "Pick plane/cylinder/cone face",
        "pick_two_vertices": "Pick two vertices",
        "placement_help": "Pair Build CS to a plate mount; adjustment order is translate, Rx, Ry, Rz.",
        "mount": "Build-plate mount",
        "coordinates_valid": "Coordinates Valid",
        "setup_ready": "Setup Ready",
        "issues": "Issues",
        "no_issues": "No current issues.",
        "ready_warning": "Ready with Warnings",
        "status_missing": "Missing",
        "status_draft": "Draft",
        "status_valid": "Valid",
        "status_dirty": "Dirty",
        "status_invalid": "Invalid",
    },
}

TUBE_CONTROL_TEXT = (
    ("title_label", "title"),
    ("subtitle_label", "subtitle"),
    ("back_button", "back"),
    ("open_button", "open"),
    ("update_source_button", "update_source"),
    ("save_button", "save"),
    ("create_operation_button", "create_operation"),
    ("model_view_button", "model_view"),
    ("machine_view_button", "machine_view"),
    ("empty_editor", "editor_empty"),
    ("part_help", "part_help"),
    ("part_confirm_button", "confirm"),
    ("machine_help", "resource_help"),
    ("machine_apply_button", "apply"),
    ("nozzle_help", "resource_help"),
    ("nozzle_interface_label", "interface"),
    ("nozzle_length_label", "length"),
    ("nozzle_collision", "collision_profile"),
    ("nozzle_apply_button", "apply"),
    ("material_help", "resource_help"),
    ("material_review", "review"),
    ("material_apply_button", "apply"),
    ("coordinate_apply_button", "apply"),
    ("coordinate_cancel_button", "cancel"),
    ("placement_help", "placement_help"),
    ("mount_label", "mount"),
    ("placement_apply_button", "apply"),
    ("placement_cancel_button", "cancel"),
    ("issue_title", "issues"),
)

_COORDINATE_SETUP_ORDER = (
    PART_NODE,
    MACHINE_NODE,
    MODEL_CS_NODE,
    BUILD_CS_NODE,
    PLACEMENT_NODE,
)
_EDITABLE_SETUP_NODES = frozenset((*_COORDINATE_SETUP_ORDER, NOZZLE_NODE, MATERIAL_NODE))


def setup_tree_node(
    selected: object,
    items: Mapping[str, object],
    report: SetupValidationReport,
) -> str:
    """Keep a valid selection or choose the next coordinate prerequisite."""

    if isinstance(selected, str) and selected in _EDITABLE_SETUP_NODES and selected in items:
        return selected
    return next(
        (node for node in _COORDINATE_SETUP_ORDER if report.state_for(node) is not NodeState.VALID),
        PART_NODE,
    )


def tube_language(language: str) -> str:
    if language not in TUBE_TEXT:
        raise ValueError(f"unsupported Tube UI language: {language}")
    return language


__all__ = ["TUBE_CONTROL_TEXT", "TUBE_TEXT", "setup_tree_node", "tube_language"]
