from __future__ import annotations

# Keep UI strings separate from widget logic so language switching stays
# simple.
# 界面文案和控件逻辑分开放，切换语言时就不用把大段字符串塞进事件处理里。
UI_TEXT = {
    "zh": {
        "app_title": "五轴混合切片软件 ({api})",
        "open_model": "打开模型",
        "load_demo": "载入示例",
        "slice": "开始切片",
        "export_gcode": "导出 G-code",
        "language": "语言",
        "language_name_zh": "中文",
        "language_name_en": "English",
        "model_group": "模型信息",
        "slice_mode": "切片模式",
        "slice_mode_hybrid": "五轴混合切片",
        "slice_mode_planar": "三轴平面切片",
        "selection_tools_section": "面片 / 组件选择 (开发中)",
        "face_selection": "面片选择",
        "face_selection_help": "打开选面后，可以在右侧预览窗口里点击三角面片；打开刷子后，按住左键拖动即可连续刷选。当前提供“基底面片”和“共形面片”两类标记；结果会缓存到 outputs/selection_cache.json，重新打开同一个模型后可以继续选择。",
        "enable_face_picking": "启用预览区选面",
        "face_pick_target": "当前选面目标",
        "face_pick_target_substrate": "基底面片",
        "face_pick_target_conformal": "共形面片",
        "face_brush": "刷子模式",
        "face_brush_help": "刷子开启后，鼠标会显示一个黑边透明圆圈。按住左键拖动时，圆圈覆盖到的可见三角面片会连续加入当前目标分组。",
        "face_brush_size": "刷子尺寸",
        "brush_size_small": "小",
        "brush_size_medium": "中",
        "brush_size_large": "大",
        "clear_substrate_faces": "清空基底面片",
        "clear_conformal_faces": "清空共形面片",
        "face_selection_summary": "面片选择状态: 基底={substrate_count}  共形={conformal_count}\n预览选面: {pick_state}  当前目标: {target}\n刷子: {brush_state}  尺寸: {brush_size}",
        "face_picking_on": "开启",
        "face_picking_off": "关闭",
        "component_selection": "组件选择",
        "substrate_component": "基底几何体",
        "conformal_components": "共形几何体",
        "transform_group": "模型摆放",
        "slicing_group": "切片参数",
        "machine_group": "机床 / G-code 标定",
        "preview_group": "预览显示",
        "preview_help": "预览窗口现在使用 OpenGL 实时渲染。左键拖动旋转，右键或中键拖动平移，滚轮缩放；拖动时会自动切换到轻量细节级别，保证像 Cura / 拓竹切片预览那样顺滑。",
        "show_mesh": "显示模型网格",
        "path_filter_waiting_tooltip": "当前还没有切片结果。这些开关会记住你的选择，切片完成后立即生效。",
        "path_filter_ready_tooltip": "勾选后显示这种路径，取消勾选后隐藏这种路径。",
        "path_kind_planar_perimeter": "核心外轮廓",
        "path_kind_planar_infill": "核心填充",
        "path_kind_conformal_perimeter": "曲面外轮廓",
        "path_kind_conformal_surface_finish": "曲面精加工主路径",
        "path_kind_conformal_infill": "曲面填充",
        "log_title": "切片 / 导出日志",
        "no_model_loaded": "尚未加载模型",
        "slice_result_placeholder": "切片结果会显示在这里",
        "transform_help": "旋转默认绕当前模型中心进行；平移沿全局 X/Y/Z 方向执行。手动摆放后会自动关闭“自动居中模型”。",
        "transform_empty": "当前未应用手动摆放变换。",
        "transform_status": "当前摆放\n旋转 (deg): X={rx:.2f}, Y={ry:.2f}, Z={rz:.2f}\n平移 (mm): X={tx:.2f}, Y={ty:.2f}, Z={tz:.2f}",
        "rotation_axis": "旋转轴",
        "rotation_angle_deg": "旋转角度 (deg)",
        "apply_rotation": "应用旋转",
        "translation_axis": "平移轴",
        "translation_distance_mm": "平移距离 (mm)",
        "apply_translation": "应用平移",
        "reset_placement": "重置摆放",
        "nozzle_diameter_mm": "喷嘴直径 (mm)",
        "layer_height_mm": "曲面层高 (mm)",
        "line_spacing_mm": "曲面线间距 (mm)",
        "perimeters": "曲面外轮廓数",
        "include_infill": "曲面填充",
        "infill_angle_deg": "曲面填充角度",
        "segment_length_mm": "离散段长 (mm)",
        "grid_step_mm": "表面采样网格 (mm)",
        "top_normal_threshold": "顶部法向筛选",
        "auto_center_model": "自动居中模型",
        "enable_planar_core": "启用回转核心优先打印",
        "auto_core_transition": "自动识别核心顶高",
        "core_transition_height_mm": "手动核心顶高 (mm)",
        "core_transition_percentile": "核心识别分位值",
        "planar_layer_height_mm": "回转核心层高 (0=跟随曲面层)",
        "planar_line_spacing_mm": "回转核心线间距 (0=跟随曲面层)",
        "planar_perimeters": "回转核心外轮廓数",
        "planar_include_infill": "回转核心填充",
        "planar_infill_angle_deg": "回转核心填充角度",
        "print_speed_mm_s": "曲面打印速度 (mm/s)",
        "planar_print_speed_mm_s": "回转核心打印速度 (mm/s)",
        "travel_speed_mm_s": "空移速度 (mm/s)",
        "travel_height_mm": "空移抬升 (mm)",
        "filament_diameter_mm": "丝材直径 (mm)",
        "extrusion_multiplier": "挤出倍率",
        "retraction_mm": "回抽长度 (mm)",
        "retract_speed_mm_s": "回抽速度 (mm/s)",
        "prime_speed_mm_s": "补料速度 (mm/s)",
        "choice_yes": "是",
        "choice_no": "否",
        "machine_intro": "当前界面按 Open5x / Freddi Hong 的硬件思路设计：U 轴让旋转床绕机器 Y 轴倾斜，V 轴让已经倾斜的床继续绕局部轴转动。下面这些偏移和零位需要按你的真机实测校准。",
        "machine_reset": "恢复 Open5x 默认值",
        "preset_summary": "预设摘要",
        "x_offset_mm": "X 偏移 (mm)",
        "y_offset_mm": "Y 偏移 (mm)",
        "z_offset_mm": "Z 偏移 (mm)",
        "rotary_center_x_mm": "旋转中心 X (mm)",
        "rotary_center_y_mm": "旋转中心 Y (mm)",
        "rotary_center_z_mm": "旋转中心 Z (mm)",
        "bed_diameter_mm": "打印床直径 (mm)",
        "rotary_scale_radius_mm": "旋转等效半径 (mm)",
        "phase_change_lift_mm": "切换到五轴时安全抬升 (mm)",
        "u_axis_sign": "U 轴方向符号",
        "v_axis_sign": "V 轴方向符号",
        "u_zero_offset_deg": "U 零位补偿 (deg)",
        "v_zero_offset_deg": "V 零位补偿 (deg)",
        "home_u_deg": "Home U (deg)",
        "home_v_deg": "Home V (deg)",
        "min_u_deg": "U 最小角度 (deg)",
        "max_u_deg": "U 最大角度 (deg)",
        "min_v_deg": "V 最小角度 (deg)",
        "max_v_deg": "V 最大角度 (deg)",
        "max_feed_mm_min": "最大进给速度 (mm/min)",
        "start_gcode_template": "起始 G-code 模板",
        "phase_change_gcode_template": "阶段切换模板",
        "end_gcode_template": "结束 G-code 模板",
        "sign_same_math": "1  (与数学模型同方向)",
        "sign_invert_direction": "-1 (反向)",
        "open_cad_model": "打开 CAD 模型",
        "save_gcode": "保存 G-code",
        "demo_model": "示例模型",
        "ready_log": "软件就绪。请先载入 STL/STEP 模型，或直接打开示例模型。",
        "reset_machine_log": "已恢复为 Open5x / Freddi Hong 风格的默认机床标定参数。",
        "loaded_model_log": "已载入模型: {path}",
        "loaded_demo_log": "已载入示例穹顶模型。",
        "selection_cache_loaded_log": "已恢复上次的面片选择: 基底 {substrate} 面, 共形 {conformal} 面。",
        "slicing_complete_log": "切片完成：共 {path_count} 条路径，总路径长度 {length:.1f} mm。",
        "machine_profile_log": "当前机床预设: {profile}",
        "warnings_header": "警告",
        "saved_gcode_log": "G-code 已保存到: {path}",
        "selection_autoclosed_log": "已智能补齐基底面片选择，新增 {added} 个邻接面。",
        "switched_planar_log": "已切换到三轴平面切片模式。",
        "rotation_applied_log": "模型已绕 {axis} 轴旋转 {angle:.2f} deg。",
        "translation_applied_log": "模型已沿 {axis} 轴平移 {distance:.2f} mm。",
        "placement_reset_log": "模型摆放已恢复到载入时状态。",
        "auto_center_disabled_log": "检测到你在手动摆放模型，已自动关闭“自动居中模型”。",
        "need_load_model": "请先载入模型。",
        "need_slice_first": "请先完成切片，再导出 G-code。",
        "missing_substrate_title": "缺少五轴基底",
        "missing_substrate_message": "你已经选择了共形面片，但还没有选择五轴打印的中心基底。\n\n是否切换到三轴平面切片模式？\n选择“是”会切到三轴模式；选择“否”则继续保留五轴模式。",
        "selection_not_closed_title": "选择区域未闭合",
        "selection_not_closed_message_small": "当前基底面片选择看起来只差一小段邻接区域。\n\n是否执行保守的智能闭合？预计会补入约 {added} 个相邻面片。",
        "selection_not_closed_message_large": "当前基底面片选择缺口较大，继续做五轴基底可能不稳定。\n\n是否切换到三轴平面切片模式？选择“否”会继续保留当前五轴设置。",
        "failed_to_load_model": "模型加载失败:\n{error}",
        "slicing_failed": "切片失败:\n{error}",
        "error_title": "五轴混合切片软件",
        "model_info_text": "名称: {name}\n来源: {source}\n顶点数: {vertex_count}  面数: {face_count}\n尺寸: {size_x:.2f} x {size_y:.2f} x {size_z:.2f} mm",
        "component_item": "组件 {index}: 面={faces} 中心=({center_x:.2f}, {center_y:.2f}, {center_z:.2f}) mm 尺寸=({size_x:.2f}, {size_y:.2f}, {size_z:.2f}) mm 离中心={radial:.2f} mm",
        "stats_summary": "路径数: {path_count}  核心层: {planar_count}  曲面层: {conformal_count}\n核心层数: {planar_layers}  核心顶高: {transition:.2f} mm\n点数: {points}  总长度: {length:.2f} mm\n表面采样点: {surface_samples}",
        "stats_warnings": "\n警告数: {count}",
    },
    "en": {
        "app_title": "Five-Axis Hybrid Slicer ({api})",
        "open_model": "Open Model",
        "load_demo": "Load Demo",
        "slice": "Slice",
        "export_gcode": "Export G-code",
        "language": "Language",
        "language_name_zh": "Chinese",
        "language_name_en": "English",
        "model_group": "Model",
        "slice_mode": "Slice Mode",
        "slice_mode_hybrid": "Hybrid Five-Axis",
        "slice_mode_planar": "Planar Three-Axis",
        "selection_tools_section": "Face / Component Selection (In Progress)",
        "face_selection": "Face Selection",
        "face_selection_help": "When face picking is enabled, click triangles directly in the preview. When brush mode is enabled, hold the left mouse button and paint over the preview to add visible triangles continuously. The selection is cached in outputs/selection_cache.json so reopening the same model can continue from the previous state.",
        "enable_face_picking": "Enable face picking in preview",
        "face_pick_target": "Face pick target",
        "face_pick_target_substrate": "Substrate faces",
        "face_pick_target_conformal": "Conformal faces",
        "face_brush": "Brush Mode",
        "face_brush_help": "With brush mode enabled, the cursor shows a transparent circle with a black outline. Hold the left mouse button and drag to add every visible triangle touched by the brush to the current target group.",
        "face_brush_size": "Brush Size",
        "brush_size_small": "Small",
        "brush_size_medium": "Medium",
        "brush_size_large": "Large",
        "clear_substrate_faces": "Clear substrate faces",
        "clear_conformal_faces": "Clear conformal faces",
        "face_selection_summary": "Face selection: substrate={substrate_count}  conformal={conformal_count}\nPreview picking: {pick_state}  Current target: {target}\nBrush: {brush_state}  Size: {brush_size}",
        "face_picking_on": "On",
        "face_picking_off": "Off",
        "component_selection": "Component Selection",
        "substrate_component": "Substrate Geometry",
        "conformal_components": "Conformal Geometries",
        "transform_group": "Model Placement",
        "slicing_group": "Slicing Parameters",
        "machine_group": "Machine / G-code Calibration",
        "preview_group": "Preview Display",
        "preview_help": "The preview now uses OpenGL for real-time rendering. Drag with the left mouse button to orbit, use right or middle drag to pan, and the wheel to zoom. While dragging, it switches to a lighter level of detail so the preview stays closer to Cura / Bambu Studio in feel.",
        "show_mesh": "Show model mesh",
        "path_filter_waiting_tooltip": "There is no slice result yet. These switches keep your choice and take effect right after slicing.",
        "path_filter_ready_tooltip": "Checked means this path type is visible in the preview. Unchecked hides it.",
        "path_kind_planar_perimeter": "Core perimeter",
        "path_kind_planar_infill": "Core infill",
        "path_kind_conformal_perimeter": "Conformal perimeter",
        "path_kind_conformal_surface_finish": "Surface-finish path",
        "path_kind_conformal_infill": "Conformal infill",
        "log_title": "Slice / Export Log",
        "no_model_loaded": "No model loaded",
        "slice_result_placeholder": "Slice result will appear here",
        "transform_help": "Rotation is applied around the current model centre. Translation follows the global X/Y/Z axes. Manual placement automatically disables auto-centering.",
        "transform_empty": "No manual placement transform has been applied.",
        "transform_status": "Current placement\nRotation (deg): X={rx:.2f}, Y={ry:.2f}, Z={rz:.2f}\nTranslation (mm): X={tx:.2f}, Y={ty:.2f}, Z={tz:.2f}",
        "rotation_axis": "Rotation Axis",
        "rotation_angle_deg": "Rotation Angle (deg)",
        "apply_rotation": "Apply Rotation",
        "translation_axis": "Translation Axis",
        "translation_distance_mm": "Translation Distance (mm)",
        "apply_translation": "Apply Translation",
        "reset_placement": "Reset Placement",
        "nozzle_diameter_mm": "Nozzle (mm)",
        "layer_height_mm": "Conformal Layer Height (mm)",
        "line_spacing_mm": "Conformal Line Spacing (mm)",
        "perimeters": "Conformal Perimeters",
        "include_infill": "Conformal Infill",
        "infill_angle_deg": "Conformal Infill Angle",
        "segment_length_mm": "Segment Length (mm)",
        "grid_step_mm": "Surface Grid (mm)",
        "top_normal_threshold": "Top Normal Filter",
        "auto_center_model": "Auto-center Model",
        "enable_planar_core": "Enable Rotary Core First",
        "auto_core_transition": "Auto Core Top Z",
        "core_transition_height_mm": "Core Top Z Override (mm)",
        "core_transition_percentile": "Core Detection Percentile",
        "planar_layer_height_mm": "Rotary Core Layer Height (0=follow)",
        "planar_line_spacing_mm": "Rotary Core Line Spacing (0=follow)",
        "planar_perimeters": "Rotary Core Perimeters",
        "planar_include_infill": "Rotary Core Infill",
        "planar_infill_angle_deg": "Rotary Core Infill Angle",
        "print_speed_mm_s": "Conformal Speed (mm/s)",
        "planar_print_speed_mm_s": "Rotary Core Speed (mm/s)",
        "travel_speed_mm_s": "Travel Speed (mm/s)",
        "travel_height_mm": "Travel Height (mm)",
        "filament_diameter_mm": "Filament Diameter (mm)",
        "extrusion_multiplier": "Extrusion Multiplier",
        "retraction_mm": "Retraction (mm)",
        "retract_speed_mm_s": "Retract Speed (mm/s)",
        "prime_speed_mm_s": "Prime Speed (mm/s)",
        "choice_yes": "Yes",
        "choice_no": "No",
        "machine_intro": "This panel follows the Open5x / Freddi Hong hardware idea: U tilts the rotary bed about the machine Y axis, and V spins the already tilted bed around its local axis. Offsets and zero angles should be measured on your real printer.",
        "machine_reset": "Reset Open5x Defaults",
        "preset_summary": "Preset Summary",
        "x_offset_mm": "X Offset (mm)",
        "y_offset_mm": "Y Offset (mm)",
        "z_offset_mm": "Z Offset (mm)",
        "rotary_center_x_mm": "Rotary Center X (mm)",
        "rotary_center_y_mm": "Rotary Center Y (mm)",
        "rotary_center_z_mm": "Rotary Center Z (mm)",
        "bed_diameter_mm": "Bed Diameter (mm)",
        "rotary_scale_radius_mm": "Rotary Radius for Feed (mm)",
        "phase_change_lift_mm": "Phase-change Lift (mm)",
        "u_axis_sign": "U Axis Sign",
        "v_axis_sign": "V Axis Sign",
        "u_zero_offset_deg": "U Zero Offset (deg)",
        "v_zero_offset_deg": "V Zero Offset (deg)",
        "home_u_deg": "Home U (deg)",
        "home_v_deg": "Home V (deg)",
        "min_u_deg": "Min U (deg)",
        "max_u_deg": "Max U (deg)",
        "min_v_deg": "Min V (deg)",
        "max_v_deg": "Max V (deg)",
        "max_feed_mm_min": "Max Feed (mm/min)",
        "start_gcode_template": "Start G-code Template",
        "phase_change_gcode_template": "Phase-change Template",
        "end_gcode_template": "End G-code Template",
        "sign_same_math": "1  (same as math model)",
        "sign_invert_direction": "-1 (invert axis direction)",
        "open_cad_model": "Open CAD Model",
        "save_gcode": "Save G-code",
        "demo_model": "Demo model",
        "ready_log": "Ready. Load an STL/STEP model or open the demo dome to start.",
        "reset_machine_log": "Reset machine parameters to the Open5x / Freddi Hong style preset.",
        "loaded_model_log": "Loaded model: {path}",
        "loaded_demo_log": "Loaded demo dome mesh.",
        "selection_cache_loaded_log": "Restored cached face selection: substrate {substrate} faces, conformal {conformal} faces.",
        "slicing_complete_log": "Slicing complete: {path_count} paths, {length:.1f} mm total path length.",
        "machine_profile_log": "Machine profile: {profile}",
        "warnings_header": "Warnings",
        "saved_gcode_log": "Saved G-code to: {path}",
        "selection_autoclosed_log": "Applied conservative smart-close to the substrate selection and added {added} neighbouring faces.",
        "switched_planar_log": "Switched to planar three-axis slicing mode.",
        "rotation_applied_log": "Rotated the model {angle:.2f} deg about the {axis} axis.",
        "translation_applied_log": "Moved the model {distance:.2f} mm along the {axis} axis.",
        "placement_reset_log": "Reset the model placement to the originally loaded state.",
        "auto_center_disabled_log": "Manual placement was applied, so auto-centering has been disabled.",
        "need_load_model": "Load a model first.",
        "need_slice_first": "Run slicing first so there is G-code to export.",
        "missing_substrate_title": "Missing Five-Axis Substrate",
        "missing_substrate_message": "You selected conformal faces but have not selected the central substrate for five-axis printing.\n\nSwitch to planar three-axis slicing?\nChoose Yes to switch to planar mode, or No to keep the current five-axis mode.",
        "selection_not_closed_title": "Selection Not Closed",
        "selection_not_closed_message_small": "The current substrate face selection appears to be missing only a small neighbouring patch.\n\nApply conservative smart-close? It is expected to add about {added} nearby faces.",
        "selection_not_closed_message_large": "The current substrate face selection still has a large gap, so the five-axis substrate may be unreliable.\n\nSwitch to planar three-axis slicing instead? Choosing No keeps the current five-axis setup.",
        "failed_to_load_model": "Failed to load model:\n{error}",
        "slicing_failed": "Slicing failed:\n{error}",
        "error_title": "Five-Axis Hybrid Slicer",
        "model_info_text": "Name: {name}\nSource: {source}\nVertices: {vertex_count}  Faces: {face_count}\nSize: {size_x:.2f} x {size_y:.2f} x {size_z:.2f} mm",
        "component_item": "Component {index}: faces={faces} center=({center_x:.2f}, {center_y:.2f}, {center_z:.2f}) mm size=({size_x:.2f}, {size_y:.2f}, {size_z:.2f}) mm radial={radial:.2f} mm",
        "stats_summary": "Paths: {path_count}  Core: {planar_count}  Conformal: {conformal_count}\nCore Layers: {planar_layers}  Core Top Z: {transition:.2f} mm\nPoints: {points}  Length: {length:.2f} mm\nSurface Samples: {surface_samples}",
        "stats_warnings": "\nWarnings: {count}",
    },
}

AXES = ("X", "Y", "Z")
PATH_KIND_ORDER = [
    "planar-perimeter",
    "planar-infill",
    "conformal-perimeter",
    "conformal-surface-finish",
    "conformal-infill",
]
PATH_KIND_LABEL_KEYS = {
    "planar-perimeter": "path_kind_planar_perimeter",
    "planar-infill": "path_kind_planar_infill",
    "conformal-perimeter": "path_kind_conformal_perimeter",
    "conformal-surface-finish": "path_kind_conformal_surface_finish",
    "conformal-infill": "path_kind_conformal_infill",
}
